<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-GameStore.Worker-3925bae1-2485-4277-8165-bc919ba9a09a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="QuestPDF" Version="2026.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameStore.Contracts\GameStore.Contracts.csproj" />
  </ItemGroup>
</Project>
