FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["GameStore.Worker/GameStore.Worker.csproj", "GameStore.Worker/"]
COPY ["GameStore.Contracts/GameStore.Contracts.csproj", "GameStore.Contracts/"]

RUN dotnet restore "GameStore.Worker/GameStore.Worker.csproj"

COPY . .

WORKDIR "/src/GameStore.Worker"
RUN dotnet build "GameStore.Worker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GameStore.Worker.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:10.0
WORKDIR /app

COPY --from=publish /app/publish .
ENTRYPOINT [ "dotnet", "GameStore.Worker.dll" ]