FROM node:20-alpine

WORKDIR /app

COPY GameStore.FE/package.json GameStore.FE/package-lock.json* ./
RUN npm install

COPY GameStore.FE/ ./

ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD ["npm", "run", "dev"]